from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 600)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(50, 100, 400, 400))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.frame.setFont(font)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.square00 = QtWidgets.QLineEdit(self.frame)
        self.square00.setGeometry(QtCore.QRect(10, 10, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square00.setFont(font)
        self.square00.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square00.setText("")
        self.square00.setObjectName("square00")
        self.square01 = QtWidgets.QLineEdit(self.frame)
        self.square01.setGeometry(QtCore.QRect(50, 10, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square01.setFont(font)
        self.square01.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square01.setText("")
        self.square01.setObjectName("square01")
        self.square02 = QtWidgets.QLineEdit(self.frame)
        self.square02.setGeometry(QtCore.QRect(90, 10, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square02.setFont(font)
        self.square02.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square02.setText("")
        self.square02.setObjectName("square02")
        self.square10 = QtWidgets.QLineEdit(self.frame)
        self.square10.setGeometry(QtCore.QRect(10, 50, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square10.setFont(font)
        self.square10.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square10.setText("")
        self.square10.setObjectName("square10")
        self.square11 = QtWidgets.QLineEdit(self.frame)
        self.square11.setGeometry(QtCore.QRect(50, 50, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square11.setFont(font)
        self.square11.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square11.setText("")
        self.square11.setObjectName("square11")
        self.square12 = QtWidgets.QLineEdit(self.frame)
        self.square12.setGeometry(QtCore.QRect(90, 50, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square12.setFont(font)
        self.square12.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square12.setText("")
        self.square12.setObjectName("square12")
        self.square20 = QtWidgets.QLineEdit(self.frame)
        self.square20.setGeometry(QtCore.QRect(10, 90, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square20.setFont(font)
        self.square20.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square20.setText("")
        self.square20.setObjectName("square20")
        self.square21 = QtWidgets.QLineEdit(self.frame)
        self.square21.setGeometry(QtCore.QRect(50, 90, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square21.setFont(font)
        self.square21.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square21.setText("")
        self.square21.setObjectName("square21")
        self.square22 = QtWidgets.QLineEdit(self.frame)
        self.square22.setGeometry(QtCore.QRect(90, 90, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square22.setFont(font)
        self.square22.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square22.setText("")
        self.square22.setObjectName("square22")

        # Grid 2
        self.square03 = QtWidgets.QLineEdit(self.frame)
        self.square03.setGeometry(QtCore.QRect(140, 10, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square03.setFont(font)
        self.square03.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square03.setText("")
        self.square03.setObjectName("square03")
        self.square04 = QtWidgets.QLineEdit(self.frame)
        self.square04.setGeometry(QtCore.QRect(180, 10, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square04.setFont(font)
        self.square04.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square04.setText("")
        self.square04.setObjectName("square04")
        self.square05 = QtWidgets.QLineEdit(self.frame)
        self.square05.setGeometry(QtCore.QRect(220, 10, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square05.setFont(font)
        self.square05.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square05.setText("")
        self.square05.setObjectName("square05")
        self.square13 = QtWidgets.QLineEdit(self.frame)
        self.square13.setGeometry(QtCore.QRect(140, 50, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square13.setFont(font)
        self.square13.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square13.setText("")
        self.square13.setObjectName("square13")
        self.square14 = QtWidgets.QLineEdit(self.frame)
        self.square14.setGeometry(QtCore.QRect(180, 50, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square14.setFont(font)
        self.square14.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square14.setText("")
        self.square14.setObjectName("square14")
        self.square15 = QtWidgets.QLineEdit(self.frame)
        self.square15.setGeometry(QtCore.QRect(220, 50, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square15.setFont(font)
        self.square15.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square15.setText("")
        self.square15.setObjectName("square15")
        self.square23 = QtWidgets.QLineEdit(self.frame)
        self.square23.setGeometry(QtCore.QRect(140, 90, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square23.setFont(font)
        self.square23.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square23.setText("")
        self.square23.setObjectName("square23")        
        self.square24 = QtWidgets.QLineEdit(self.frame)
        self.square24.setGeometry(QtCore.QRect(180, 90, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square24.setFont(font)
        self.square24.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square24.setText("")
        self.square24.setObjectName("square24")        
        self.square25 = QtWidgets.QLineEdit(self.frame)
        self.square25.setGeometry(QtCore.QRect(220, 90, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square25.setFont(font)
        self.square25.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square25.setText("")
        self.square25.setObjectName("square25")
        
        # Grid 3
        self.square06 = QtWidgets.QLineEdit(self.frame)
        self.square06.setGeometry(QtCore.QRect(270, 10, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square06.setFont(font)
        self.square06.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square06.setText("")
        self.square06.setObjectName("square06")
        self.square07 = QtWidgets.QLineEdit(self.frame)
        self.square07.setGeometry(QtCore.QRect(310, 10, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square07.setFont(font)
        self.square07.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square07.setText("")
        self.square07.setObjectName("square07")
        self.square08 = QtWidgets.QLineEdit(self.frame)
        self.square08.setGeometry(QtCore.QRect(350, 10, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square08.setFont(font)
        self.square08.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square08.setText("")
        self.square08.setObjectName("square08")
        self.square16 = QtWidgets.QLineEdit(self.frame)
        self.square16.setGeometry(QtCore.QRect(270, 50, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square16.setFont(font)
        self.square16.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square16.setText("")
        self.square16.setObjectName("square16")
        self.square17 = QtWidgets.QLineEdit(self.frame)
        self.square17.setGeometry(QtCore.QRect(310, 50, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square17.setFont(font)
        self.square17.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square17.setText("")
        self.square17.setObjectName("square17")
        self.square18 = QtWidgets.QLineEdit(self.frame)
        self.square18.setGeometry(QtCore.QRect(350, 50, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square18.setFont(font)
        self.square18.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square18.setText("")
        self.square18.setObjectName("square18")
        self.square26 = QtWidgets.QLineEdit(self.frame)
        self.square26.setGeometry(QtCore.QRect(270, 90, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square26.setFont(font)
        self.square26.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square26.setText("")
        self.square26.setObjectName("square26")        
        self.square27 = QtWidgets.QLineEdit(self.frame)
        self.square27.setGeometry(QtCore.QRect(310, 90, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square27.setFont(font)
        self.square27.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square27.setText("")
        self.square27.setObjectName("square27")        
        self.square28 = QtWidgets.QLineEdit(self.frame)
        self.square28.setGeometry(QtCore.QRect(350, 90, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square28.setFont(font)
        self.square28.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square28.setText("")
        self.square28.setObjectName("square28")
        
        # Grid 4
        self.square30 = QtWidgets.QLineEdit(self.frame)
        self.square30.setGeometry(QtCore.QRect(10, 140, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square30.setFont(font)
        self.square30.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square30.setText("")
        self.square30.setObjectName("square30")
        self.square31 = QtWidgets.QLineEdit(self.frame)
        self.square31.setGeometry(QtCore.QRect(50, 140, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square31.setFont(font)
        self.square31.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square31.setText("")
        self.square31.setObjectName("square31")
        self.square32 = QtWidgets.QLineEdit(self.frame)
        self.square32.setGeometry(QtCore.QRect(90, 140, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square32.setFont(font)
        self.square32.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square32.setText("")
        self.square32.setObjectName("square32")
        self.square40 = QtWidgets.QLineEdit(self.frame)
        self.square40.setGeometry(QtCore.QRect(10, 180, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square40.setFont(font)
        self.square40.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square40.setText("")
        self.square40.setObjectName("square40")
        self.square41 = QtWidgets.QLineEdit(self.frame)
        self.square41.setGeometry(QtCore.QRect(50, 180, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square41.setFont(font)
        self.square41.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square41.setText("")
        self.square41.setObjectName("square41")
        self.square42 = QtWidgets.QLineEdit(self.frame)
        self.square42.setGeometry(QtCore.QRect(90, 180, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square42.setFont(font)
        self.square42.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square42.setText("")
        self.square42.setObjectName("square42")
        self.square50 = QtWidgets.QLineEdit(self.frame)
        self.square50.setGeometry(QtCore.QRect(10, 220, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square50.setFont(font)
        self.square50.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square50.setText("")
        self.square50.setObjectName("square50")
        self.square51 = QtWidgets.QLineEdit(self.frame)
        self.square51.setGeometry(QtCore.QRect(50, 220, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square51.setFont(font)
        self.square51.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square51.setText("")
        self.square51.setObjectName("square51")
        self.square52 = QtWidgets.QLineEdit(self.frame)
        self.square52.setGeometry(QtCore.QRect(90, 220, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square52.setFont(font)
        self.square52.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square52.setText("")
        self.square52.setObjectName("square52")

        # Grid 5
        self.square33 = QtWidgets.QLineEdit(self.frame)
        self.square33.setGeometry(QtCore.QRect(140, 140, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square33.setFont(font)
        self.square33.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square33.setText("")
        self.square33.setObjectName("square33")
        self.square34 = QtWidgets.QLineEdit(self.frame)
        self.square34.setGeometry(QtCore.QRect(180, 140, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square34.setFont(font)
        self.square34.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square34.setText("")
        self.square34.setObjectName("square34")
        self.square35 = QtWidgets.QLineEdit(self.frame)
        self.square35.setGeometry(QtCore.QRect(220, 140, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square35.setFont(font)
        self.square35.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square35.setText("")
        self.square35.setObjectName("square35")
        self.square43 = QtWidgets.QLineEdit(self.frame)
        self.square43.setGeometry(QtCore.QRect(140, 180, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square43.setFont(font)
        self.square43.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square43.setText("")
        self.square43.setObjectName("square43")
        self.square44 = QtWidgets.QLineEdit(self.frame)
        self.square44.setGeometry(QtCore.QRect(180, 180, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square44.setFont(font)
        self.square44.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square44.setText("")
        self.square44.setObjectName("square44")
        self.square45 = QtWidgets.QLineEdit(self.frame)
        self.square45.setGeometry(QtCore.QRect(220, 180, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square45.setFont(font)
        self.square45.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square45.setText("")
        self.square45.setObjectName("square45")
        self.square53 = QtWidgets.QLineEdit(self.frame)
        self.square53.setGeometry(QtCore.QRect(140, 220, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square53.setFont(font)
        self.square53.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square53.setText("")
        self.square53.setObjectName("square53")
        self.square54 = QtWidgets.QLineEdit(self.frame)
        self.square54.setGeometry(QtCore.QRect(180, 220, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square54.setFont(font)
        self.square54.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square54.setText("")
        self.square54.setObjectName("square54")
        self.square55 = QtWidgets.QLineEdit(self.frame)
        self.square55.setGeometry(QtCore.QRect(220, 220, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square55.setFont(font)
        self.square55.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square55.setText("")
        self.square55.setObjectName("square55")

        # Grid 6
        self.square36 = QtWidgets.QLineEdit(self.frame)
        self.square36.setGeometry(QtCore.QRect(270, 140, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square36.setFont(font)
        self.square36.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square36.setText("")
        self.square36.setObjectName("square36")
        self.square37 = QtWidgets.QLineEdit(self.frame)
        self.square37.setGeometry(QtCore.QRect(310, 140, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square37.setFont(font)
        self.square37.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square37.setText("")
        self.square37.setObjectName("square37")
        self.square38 = QtWidgets.QLineEdit(self.frame)
        self.square38.setGeometry(QtCore.QRect(350, 140, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square38.setFont(font)
        self.square38.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square38.setText("")
        self.square38.setObjectName("square38")
        self.square46 = QtWidgets.QLineEdit(self.frame)
        self.square46.setGeometry(QtCore.QRect(270, 180, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square46.setFont(font)
        self.square46.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square46.setText("")
        self.square46.setObjectName("square46")
        self.square47 = QtWidgets.QLineEdit(self.frame)
        self.square47.setGeometry(QtCore.QRect(310, 180, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square47.setFont(font)
        self.square47.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square47.setText("")
        self.square47.setObjectName("square47")
        self.square48 = QtWidgets.QLineEdit(self.frame)
        self.square48.setGeometry(QtCore.QRect(350, 180, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square48.setFont(font)
        self.square48.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square48.setText("")
        self.square48.setObjectName("square48")
        self.square56 = QtWidgets.QLineEdit(self.frame)
        self.square56.setGeometry(QtCore.QRect(270, 220, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square56.setFont(font)
        self.square56.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square56.setText("")
        self.square56.setObjectName("square56")
        self.square57 = QtWidgets.QLineEdit(self.frame)
        self.square57.setGeometry(QtCore.QRect(310, 220, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square57.setFont(font)
        self.square57.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square57.setText("")
        self.square57.setObjectName("square57")
        self.square58 = QtWidgets.QLineEdit(self.frame)
        self.square58.setGeometry(QtCore.QRect(350, 220, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square58.setFont(font)
        self.square58.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square58.setText("")
        self.square58.setObjectName("square58")

        # Grid 7
        self.square60 = QtWidgets.QLineEdit(self.frame)
        self.square60.setGeometry(QtCore.QRect(10, 270, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square60.setFont(font)
        self.square60.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square60.setText("")
        self.square60.setObjectName("square60")
        self.square61 = QtWidgets.QLineEdit(self.frame)
        self.square61.setGeometry(QtCore.QRect(50, 270, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square61.setFont(font)
        self.square61.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square61.setText("")
        self.square61.setObjectName("square61")
        self.square62 = QtWidgets.QLineEdit(self.frame)
        self.square62.setGeometry(QtCore.QRect(90, 270, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square62.setFont(font)
        self.square62.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square62.setText("")
        self.square62.setObjectName("square62")
        self.square70 = QtWidgets.QLineEdit(self.frame)
        self.square70.setGeometry(QtCore.QRect(10, 310, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square70.setFont(font)
        self.square70.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square70.setText("")
        self.square70.setObjectName("square70")
        self.square71 = QtWidgets.QLineEdit(self.frame)
        self.square71.setGeometry(QtCore.QRect(50, 310, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square71.setFont(font)
        self.square71.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square71.setText("")
        self.square71.setObjectName("square71")
        self.square72 = QtWidgets.QLineEdit(self.frame)
        self.square72.setGeometry(QtCore.QRect(90, 310, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square72.setFont(font)
        self.square72.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square72.setText("")
        self.square72.setObjectName("square72")
        self.square80 = QtWidgets.QLineEdit(self.frame)
        self.square80.setGeometry(QtCore.QRect(10, 350, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square80.setFont(font)
        self.square80.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square80.setText("")
        self.square80.setObjectName("square80")
        self.square81 = QtWidgets.QLineEdit(self.frame)
        self.square81.setGeometry(QtCore.QRect(50, 350, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square81.setFont(font)
        self.square81.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square81.setText("")
        self.square81.setObjectName("square81")
        self.square82 = QtWidgets.QLineEdit(self.frame)
        self.square82.setGeometry(QtCore.QRect(90, 350, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square82.setFont(font)
        self.square82.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square82.setText("")
        self.square82.setObjectName("square82")

        # Grid 8
        self.square63 = QtWidgets.QLineEdit(self.frame)
        self.square63.setGeometry(QtCore.QRect(140, 270, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square63.setFont(font)
        self.square63.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square63.setText("")
        self.square63.setObjectName("square63")
        self.square64 = QtWidgets.QLineEdit(self.frame)
        self.square64.setGeometry(QtCore.QRect(180, 270, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square64.setFont(font)
        self.square64.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square64.setText("")
        self.square64.setObjectName("square64")
        self.square65 = QtWidgets.QLineEdit(self.frame)
        self.square65.setGeometry(QtCore.QRect(220, 270, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square65.setFont(font)
        self.square65.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square65.setText("")
        self.square65.setObjectName("square65")
        self.square73 = QtWidgets.QLineEdit(self.frame)
        self.square73.setGeometry(QtCore.QRect(140, 310, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square73.setFont(font)
        self.square73.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square73.setText("")
        self.square73.setObjectName("square73")
        self.square74 = QtWidgets.QLineEdit(self.frame)
        self.square74.setGeometry(QtCore.QRect(180, 310, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square74.setFont(font)
        self.square74.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square74.setText("")
        self.square74.setObjectName("square74")
        self.square75 = QtWidgets.QLineEdit(self.frame)
        self.square75.setGeometry(QtCore.QRect(220, 310, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square75.setFont(font)
        self.square75.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square75.setText("")
        self.square75.setObjectName("square75")
        self.square83 = QtWidgets.QLineEdit(self.frame)
        self.square83.setGeometry(QtCore.QRect(140, 350, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square83.setFont(font)
        self.square83.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square83.setText("")
        self.square83.setObjectName("square83")
        self.square84 = QtWidgets.QLineEdit(self.frame)
        self.square84.setGeometry(QtCore.QRect(180, 350, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square84.setFont(font)
        self.square84.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square84.setText("")
        self.square84.setObjectName("square84")
        self.square85 = QtWidgets.QLineEdit(self.frame)
        self.square85.setGeometry(QtCore.QRect(220, 350, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square85.setFont(font)
        self.square85.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square85.setText("")
        self.square85.setObjectName("square85")

        # Grid 9
        self.square66 = QtWidgets.QLineEdit(self.frame)
        self.square66.setGeometry(QtCore.QRect(270, 270, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square66.setFont(font)
        self.square66.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square66.setText("")
        self.square66.setObjectName("square66")
        self.square67 = QtWidgets.QLineEdit(self.frame)
        self.square67.setGeometry(QtCore.QRect(310, 270, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square67.setFont(font)
        self.square67.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square67.setText("")
        self.square67.setObjectName("square67")
        self.square68 = QtWidgets.QLineEdit(self.frame)
        self.square68.setGeometry(QtCore.QRect(350, 270, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square68.setFont(font)
        self.square68.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square68.setText("")
        self.square68.setObjectName("square68")
        self.square76 = QtWidgets.QLineEdit(self.frame)
        self.square76.setGeometry(QtCore.QRect(270, 310, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square76.setFont(font)
        self.square76.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square76.setText("")
        self.square76.setObjectName("square76")
        self.square77 = QtWidgets.QLineEdit(self.frame)
        self.square77.setGeometry(QtCore.QRect(310, 310, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square77.setFont(font)
        self.square77.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square77.setText("")
        self.square77.setObjectName("square77")
        self.square78 = QtWidgets.QLineEdit(self.frame)
        self.square78.setGeometry(QtCore.QRect(350, 310, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square78.setFont(font)
        self.square78.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square78.setText("")
        self.square78.setObjectName("square78")
        self.square86 = QtWidgets.QLineEdit(self.frame)
        self.square86.setGeometry(QtCore.QRect(270, 350, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square86.setFont(font)
        self.square86.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square86.setText("")
        self.square86.setObjectName("square86")
        self.square87 = QtWidgets.QLineEdit(self.frame)
        self.square87.setGeometry(QtCore.QRect(310, 350, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square87.setFont(font)
        self.square87.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square87.setText("")
        self.square87.setObjectName("square87")
        self.square88 = QtWidgets.QLineEdit(self.frame)
        self.square88.setGeometry(QtCore.QRect(350, 350, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.square88.setFont(font)
        self.square88.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.square88.setText("")
        self.square88.setObjectName("square88")
        
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(205, 510, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.submit.setFont(font)
        self.submit.setStatusTip("")
        self.submit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.submit.setObjectName("submit")
        
        self.sudokuLabel = QtWidgets.QLabel(self.centralwidget)
        self.sudokuLabel.setGeometry(QtCore.QRect(150, 5, 191, 48))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.sudokuLabel.setFont(font)
        self.sudokuLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sudokuLabel.setObjectName("sudokuLabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 70, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.submit.clicked.connect(self.submitClicked)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sudoku"))
        self.submit.setText(_translate("MainWindow", "SUBMIT"))
        self.sudokuLabel.setText(_translate("MainWindow", "SUDOKU"))
        self.label.setText(_translate("MainWindow", "Enter the numbers to solve the puzzle!"))
    
    def submitClicked(self):
        # Getting inputs
        # Row 1
        board[0][0] = 0 if (self.square00.text() == '') else int(self.square00.text())
        board[0][1] = 0 if (self.square01.text() == '') else int(self.square01.text())
        board[0][2] = 0 if (self.square02.text() == '') else int(self.square02.text())
        board[0][3] = 0 if (self.square03.text() == '') else int(self.square03.text())
        board[0][4] = 0 if (self.square04.text() == '') else int(self.square04.text())
        board[0][5] = 0 if (self.square05.text() == '') else int(self.square05.text())
        board[0][6] = 0 if (self.square06.text() == '') else int(self.square06.text())
        board[0][7] = 0 if (self.square07.text() == '') else int(self.square07.text())
        board[0][8] = 0 if (self.square08.text() == '') else int(self.square08.text())

        # Row 2
        board[1][0] = 0 if (self.square10.text() == '') else int(self.square10.text())
        board[1][1] = 0 if (self.square11.text() == '') else int(self.square11.text())
        board[1][2] = 0 if (self.square12.text() == '') else int(self.square12.text())
        board[1][3] = 0 if (self.square13.text() == '') else int(self.square13.text())
        board[1][4] = 0 if (self.square14.text() == '') else int(self.square14.text())
        board[1][5] = 0 if (self.square15.text() == '') else int(self.square15.text())
        board[1][6] = 0 if (self.square16.text() == '') else int(self.square16.text())
        board[1][7] = 0 if (self.square17.text() == '') else int(self.square17.text())
        board[1][8] = 0 if (self.square18.text() == '') else int(self.square18.text())

        # Row 3
        board[2][0] = 0 if (self.square20.text() == '') else int(self.square20.text())
        board[2][1] = 0 if (self.square21.text() == '') else int(self.square21.text())
        board[2][2] = 0 if (self.square22.text() == '') else int(self.square22.text())
        board[2][3] = 0 if (self.square23.text() == '') else int(self.square23.text())
        board[2][4] = 0 if (self.square24.text() == '') else int(self.square24.text())
        board[2][5] = 0 if (self.square25.text() == '') else int(self.square25.text())
        board[2][6] = 0 if (self.square26.text() == '') else int(self.square26.text())
        board[2][7] = 0 if (self.square27.text() == '') else int(self.square27.text())
        board[2][8] = 0 if (self.square28.text() == '') else int(self.square28.text())

        # Row 4
        board[3][0] = 0 if (self.square30.text() == '') else int(self.square30.text())
        board[3][1] = 0 if (self.square31.text() == '') else int(self.square31.text())
        board[3][2] = 0 if (self.square32.text() == '') else int(self.square32.text())
        board[3][3] = 0 if (self.square33.text() == '') else int(self.square33.text())
        board[3][4] = 0 if (self.square34.text() == '') else int(self.square34.text())
        board[3][5] = 0 if (self.square35.text() == '') else int(self.square35.text())
        board[3][6] = 0 if (self.square36.text() == '') else int(self.square36.text())
        board[3][7] = 0 if (self.square37.text() == '') else int(self.square37.text())
        board[3][8] = 0 if (self.square38.text() == '') else int(self.square38.text())

        # Row 5
        board[4][0] = 0 if (self.square40.text() == '') else int(self.square40.text())
        board[4][1] = 0 if (self.square41.text() == '') else int(self.square41.text())
        board[4][2] = 0 if (self.square42.text() == '') else int(self.square42.text())
        board[4][3] = 0 if (self.square43.text() == '') else int(self.square43.text())
        board[4][4] = 0 if (self.square44.text() == '') else int(self.square44.text())
        board[4][5] = 0 if (self.square45.text() == '') else int(self.square45.text())
        board[4][6] = 0 if (self.square46.text() == '') else int(self.square46.text())
        board[4][7] = 0 if (self.square47.text() == '') else int(self.square47.text())
        board[4][8] = 0 if (self.square48.text() == '') else int(self.square48.text())

        # Row 6
        board[5][0] = 0 if (self.square50.text() == '') else int(self.square50.text())
        board[5][1] = 0 if (self.square51.text() == '') else int(self.square51.text())
        board[5][2] = 0 if (self.square52.text() == '') else int(self.square52.text())
        board[5][3] = 0 if (self.square53.text() == '') else int(self.square53.text())
        board[5][4] = 0 if (self.square54.text() == '') else int(self.square54.text())
        board[5][5] = 0 if (self.square55.text() == '') else int(self.square55.text())
        board[5][6] = 0 if (self.square56.text() == '') else int(self.square56.text())
        board[5][7] = 0 if (self.square57.text() == '') else int(self.square57.text())
        board[5][8] = 0 if (self.square58.text() == '') else int(self.square58.text())

        # Row 7
        board[6][0] = 0 if (self.square60.text() == '') else int(self.square60.text())
        board[6][1] = 0 if (self.square61.text() == '') else int(self.square61.text())
        board[6][2] = 0 if (self.square62.text() == '') else int(self.square62.text())
        board[6][3] = 0 if (self.square63.text() == '') else int(self.square63.text())
        board[6][4] = 0 if (self.square64.text() == '') else int(self.square64.text())
        board[6][5] = 0 if (self.square65.text() == '') else int(self.square65.text())
        board[6][6] = 0 if (self.square66.text() == '') else int(self.square66.text())
        board[6][7] = 0 if (self.square67.text() == '') else int(self.square67.text())
        board[6][8] = 0 if (self.square68.text() == '') else int(self.square68.text())

        # Row 8
        board[7][0] = 0 if (self.square70.text() == '') else int(self.square70.text())
        board[7][1] = 0 if (self.square71.text() == '') else int(self.square71.text())
        board[7][2] = 0 if (self.square72.text() == '') else int(self.square72.text())
        board[7][3] = 0 if (self.square73.text() == '') else int(self.square73.text())
        board[7][4] = 0 if (self.square74.text() == '') else int(self.square74.text())
        board[7][5] = 0 if (self.square75.text() == '') else int(self.square75.text())
        board[7][6] = 0 if (self.square76.text() == '') else int(self.square76.text())
        board[7][7] = 0 if (self.square77.text() == '') else int(self.square77.text())
        board[7][8] = 0 if (self.square78.text() == '') else int(self.square78.text())

        # Row 9
        board[8][0] = 0 if (self.square80.text() == '') else int(self.square80.text())
        board[8][1] = 0 if (self.square81.text() == '') else int(self.square81.text())
        board[8][2] = 0 if (self.square82.text() == '') else int(self.square82.text())
        board[8][3] = 0 if (self.square83.text() == '') else int(self.square83.text())
        board[8][4] = 0 if (self.square84.text() == '') else int(self.square84.text())
        board[8][5] = 0 if (self.square85.text() == '') else int(self.square85.text())
        board[8][6] = 0 if (self.square86.text() == '') else int(self.square86.text())
        board[8][7] = 0 if (self.square87.text() == '') else int(self.square87.text())
        board[8][8] = 0 if (self.square88.text() == '') else int(self.square88.text())

        # Solve the puzzle
        solver(board)
        
        # Output the solved board
        # Row 1
        self.square00.setText(str(board[0][0]))
        self.square01.setText(str(board[0][1]))
        self.square02.setText(str(board[0][2]))
        self.square03.setText(str(board[0][3]))
        self.square04.setText(str(board[0][4]))
        self.square05.setText(str(board[0][5]))
        self.square06.setText(str(board[0][6]))
        self.square07.setText(str(board[0][7]))
        self.square08.setText(str(board[0][8]))

        # Row 2
        self.square10.setText(str(board[1][0]))
        self.square11.setText(str(board[1][1]))
        self.square12.setText(str(board[1][2]))
        self.square13.setText(str(board[1][3]))
        self.square14.setText(str(board[1][4]))
        self.square15.setText(str(board[1][5]))
        self.square16.setText(str(board[1][6]))
        self.square17.setText(str(board[1][7]))
        self.square18.setText(str(board[1][8]))

        # Row 3
        self.square20.setText(str(board[2][0]))
        self.square21.setText(str(board[2][1]))
        self.square22.setText(str(board[2][2]))
        self.square23.setText(str(board[2][3]))
        self.square24.setText(str(board[2][4]))
        self.square25.setText(str(board[2][5]))
        self.square26.setText(str(board[2][6]))
        self.square27.setText(str(board[2][7]))
        self.square28.setText(str(board[2][8]))

        # Row 4
        self.square30.setText(str(board[3][0]))
        self.square31.setText(str(board[3][1]))
        self.square32.setText(str(board[3][2]))
        self.square33.setText(str(board[3][3]))
        self.square34.setText(str(board[3][4]))
        self.square35.setText(str(board[3][5]))
        self.square36.setText(str(board[3][6]))
        self.square37.setText(str(board[3][7]))
        self.square38.setText(str(board[3][8]))

        # Row 5
        self.square40.setText(str(board[4][0]))
        self.square41.setText(str(board[4][1]))
        self.square42.setText(str(board[4][2]))
        self.square43.setText(str(board[4][3]))
        self.square44.setText(str(board[4][4]))
        self.square45.setText(str(board[4][5]))
        self.square46.setText(str(board[4][6]))
        self.square47.setText(str(board[4][7]))
        self.square48.setText(str(board[4][8]))

        # Row 6
        self.square50.setText(str(board[5][0]))
        self.square51.setText(str(board[5][1]))
        self.square52.setText(str(board[5][2]))
        self.square53.setText(str(board[5][3]))
        self.square54.setText(str(board[5][4]))
        self.square55.setText(str(board[5][5]))
        self.square56.setText(str(board[5][6]))
        self.square57.setText(str(board[5][7]))
        self.square58.setText(str(board[5][8]))

        # Row 7
        self.square60.setText(str(board[6][0]))
        self.square61.setText(str(board[6][1]))
        self.square62.setText(str(board[6][2]))
        self.square63.setText(str(board[6][3]))
        self.square64.setText(str(board[6][4]))
        self.square65.setText(str(board[6][5]))
        self.square66.setText(str(board[6][6]))
        self.square67.setText(str(board[6][7]))
        self.square68.setText(str(board[6][8]))

        # Row 8
        self.square70.setText(str(board[7][0]))
        self.square71.setText(str(board[7][1]))
        self.square72.setText(str(board[7][2]))
        self.square73.setText(str(board[7][3]))
        self.square74.setText(str(board[7][4]))
        self.square75.setText(str(board[7][5]))
        self.square76.setText(str(board[7][6]))
        self.square77.setText(str(board[7][7]))
        self.square78.setText(str(board[7][8]))

        # Row 9
        self.square80.setText(str(board[8][0]))
        self.square81.setText(str(board[8][1]))
        self.square82.setText(str(board[8][2]))
        self.square83.setText(str(board[8][3]))
        self.square84.setText(str(board[8][4]))
        self.square85.setText(str(board[8][5]))
        self.square86.setText(str(board[8][6]))
        self.square87.setText(str(board[8][7]))
        self.square88.setText(str(board[8][8]))

def solver(board):
    row = -1
    col = -1
    empty = True

    # check for empty key
    for i in range(len(board)):
        for j in range(len(board[i])):
            if (board[i][j] == 0):
                row = i
                col = j
                empty = False
                break

        if (not empty):
            break
    
    if (empty):
        return True
    
    # backtracking
    for number in range(1, 10):
        if (isSafe(board, row, col, number)):
            board[row][col] = number
            if (solver(board)):
                return True
            else:
                board[row][col] = 0
    
    return False;

def isSafe(board, row, col, number):
    # check for rows and cols
    for i in range(len(board)):
        if (board[row][i] == number):
            return False
        
        if (board[i][col] == number):
            return False
    
    # check grid
    rowStart = (row // 3) * 3
    colStart = (col // 3) * 3

    for r in range(rowStart, rowStart + 3):
        for c in range(colStart, colStart + 3):
            if (board[r][c] == number):
                return False
    
    return True

        

if __name__ == "__main__":
    import sys
    board = [
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0]
]
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
